"""add_missing_listing_fields

Revision ID: f3e0d91517cf
Revises: 5e6f7a8b9c0d
Create Date: 2025-12-24 20:04:36.219416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3e0d91517cf'
down_revision: Union[str, None] = '5e6f7a8b9c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('customer_count', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('listings', sa.Column('domain_included', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('listings', sa.Column('source_code_included', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('listings', sa.Column('customer_data_included', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'customer_data_included')
    op.drop_column('listings', 'source_code_included')
    op.drop_column('listings', 'domain_included')
    op.drop_column('listings', 'customer_count')
    # ### end Alembic commands ###
