"""Add role to users

Revision ID: 3bbcba13fff8
Revises: f3e0d91517cf
Create Date: 2026-01-02 13:55:30.716289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bbcba13fff8'
down_revision: Union[str, None] = 'f3e0d91517cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escrows', sa.Column('on_chain_id', sa.Numeric(precision=20, scale=0), nullable=True))
    op.alter_column('escrows', 'offer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_escrows_offer_id'), table_name='escrows')
    op.create_index(op.f('ix_escrows_on_chain_id'), 'escrows', ['on_chain_id'], unique=False)
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    # Create enum type first
    user_role_enum = sa.Enum('user', 'arbitrator', 'admin', name='userrole')
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', user_role_enum, nullable=False, server_default='user'))
    op.drop_constraint(op.f('uq_users_wallet_address'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=False)
    op.create_unique_constraint(op.f('uq_users_wallet_address'), 'users', ['wallet_address'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'role')
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    op.drop_index(op.f('ix_escrows_on_chain_id'), table_name='escrows')
    op.create_index(op.f('ix_escrows_offer_id'), 'escrows', ['offer_id'], unique=False)
    op.alter_column('escrows', 'offer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('escrows', 'on_chain_id')
    # ### end Alembic commands ###
