"""add revenue_history and verified_level

Revision ID: dba02a4e9b49
Revises: 3bbcba13fff8
Create Date: 2026-01-04 21:50:02.283277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba02a4e9b49'
down_revision: Union[str, None] = '3bbcba13fff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('view_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('viewer_ip_hash', sa.String(length=64), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_view_log_listing_date', 'view_logs', ['listing_id', 'viewed_at'], unique=False)
    op.create_index('idx_view_log_listing_ip', 'view_logs', ['listing_id', 'viewer_ip_hash'], unique=False)
    op.create_index('idx_view_log_viewed_at', 'view_logs', ['viewed_at'], unique=False)
    op.add_column('listings', sa.Column('revenue_history', sa.JSON(), nullable=True))
    op.add_column('listings', sa.Column('verified_level', sa.Integer(), server_default='0', nullable=False))
    op.add_column('listings', sa.Column('view_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('listings', sa.Column('view_count_7d', sa.Integer(), server_default='0', nullable=False))
    op.add_column('listings', sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'last_viewed_at')
    op.drop_column('listings', 'view_count_7d')
    op.drop_column('listings', 'view_count')
    op.drop_column('listings', 'verified_level')
    op.drop_column('listings', 'revenue_history')
    op.drop_index('idx_view_log_viewed_at', table_name='view_logs')
    op.drop_index('idx_view_log_listing_ip', table_name='view_logs')
    op.drop_index('idx_view_log_listing_date', table_name='view_logs')
    op.drop_table('view_logs')
    # ### end Alembic commands ###
