"""add_vault_tables

Revision ID: c75ed3b58a69
Revises: 3d89bf9585f1
Create Date: 2026-01-20 14:29:34.691992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75ed3b58a69'
down_revision: Union[str, None] = '3d89bf9585f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_data', sa.LargeBinary(), nullable=False),
    sa.Column('ephemeral_public_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_entries_listing_id'), 'vault_entries', ['listing_id'], unique=True)
    op.create_table('vault_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vault_entry_id', sa.UUID(), nullable=False),
    sa.Column('recipient_address', sa.String(length=42), nullable=False),
    sa.Column('recipient_role', sa.Enum('BUYER', 'SELLER', 'ARBITRATOR', name='vaultrole'), nullable=False),
    sa.Column('encrypted_ephemeral_private_key', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vault_entry_id'], ['vault_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_keys_id'), 'vault_keys', ['id'], unique=False)
    op.create_index(op.f('ix_vault_keys_vault_entry_id'), 'vault_keys', ['vault_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vault_keys_vault_entry_id'), table_name='vault_keys')
    op.drop_index(op.f('ix_vault_keys_id'), table_name='vault_keys')
    op.drop_table('vault_keys')
    op.drop_index(op.f('ix_vault_entries_listing_id'), table_name='vault_entries')
    op.drop_table('vault_entries')
    # ### end Alembic commands ###
