"""add_stripe_account_id

Revision ID: 5dde65ca7de8
Revises: dba02a4e9b49
Create Date: 2026-01-15 22:18:07.270436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dde65ca7de8'
down_revision: Union[str, None] = 'dba02a4e9b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_account_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stripe_account_id')
    # ### end Alembic commands ###
