"""Add missing verification types

Revision ID: 7f64916df154
Revises: e172cf214f2e
Create Date: 2026-01-21 00:35:04.840421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f64916df154'
down_revision: Union[str, None] = 'e172cf214f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE verificationtype ADD VALUE 'revenue_manual'")
        op.execute("ALTER TYPE verificationtype ADD VALUE 'identity'")
        op.execute("ALTER TYPE verificationtype ADD VALUE 'repo_snapshot'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
