"""add buyer_public_key to escrow

Revision ID: c0057bf970c4
Revises: 7f64916df154
Create Date: 2026-01-21 07:21:22.423509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0057bf970c4'
down_revision: Union[str, None] = '7f64916df154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escrows', sa.Column('buyer_public_key', sa.String(length=130), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('escrows', 'buyer_public_key')
    # ### end Alembic commands ###
