"""add_images_to_listings

Revision ID: 8e76a426ad72
Revises: b1859cb870b6
Create Date: 2026-01-26 09:54:27.832346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e76a426ad72'
down_revision: Union[str, None] = 'b1859cb870b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'images')
    # ### end Alembic commands ###
