"""Add notification preferences

Revision ID: 3d89bf9585f1
Revises: ac4902688f17
Create Date: 2026-01-20 08:58:57.287199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d89bf9585f1'
down_revision: Union[str, None] = 'ac4902688f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_on_offer', sa.Integer(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('email_on_status', sa.Integer(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('marketing_drops', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'marketing_drops')
    op.drop_column('users', 'email_on_status')
    op.drop_column('users', 'email_on_offer')
    # ### end Alembic commands ###
