"""add_on_chain_id_to_offers

Revision ID: ac4902688f17
Revises: 25a2b9272b35
Create Date: 2026-01-19 17:45:03.465323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4902688f17'
down_revision: Union[str, None] = '25a2b9272b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('on_chain_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_offers_on_chain_id'), 'offers', ['on_chain_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_on_chain_id'), table_name='offers')
    op.drop_column('offers', 'on_chain_id')
    # ### end Alembic commands ###
