"""remove_passkeys

Revision ID: e172cf214f2e
Revises: c75ed3b58a69
Create Date: 2026-01-21 00:18:50.576653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e172cf214f2e'
down_revision: Union[str, None] = 'c75ed3b58a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_credentials_credential_id'), table_name='user_credentials')
    op.drop_index(op.f('ix_user_credentials_user_id'), table_name='user_credentials')
    op.drop_table('user_credentials')
    op.drop_column('users', 'challenge')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('challenge', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.create_table('user_credentials',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('credential_id', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('public_key', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('sign_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transports', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_credentials_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', 'credential_id', name=op.f('user_credentials_pkey'))
    )
    op.create_index(op.f('ix_user_credentials_user_id'), 'user_credentials', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_credentials_credential_id'), 'user_credentials', ['credential_id'], unique=False)
    # ### end Alembic commands ###
