"""Add EscrowEvent table

Revision ID: bd851a7d37e1
Revises: 8e76a426ad72
Create Date: 2026-01-28 22:36:47.064577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd851a7d37e1'
down_revision: Union[str, None] = '8e76a426ad72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escrow_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('escrow_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('created', 'funded', 'assets_uploaded', 'delivered', 'confirmed', 'disputed', 'resolved', 'completed', 'cancelled', 'refunded', name='escroweventtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escrow_events_escrow_id'), 'escrow_events', ['escrow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_escrow_events_escrow_id'), table_name='escrow_events')
    op.drop_table('escrow_events')
    # ### end Alembic commands ###
