[package]
name = "escrow"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk.workspace = true
ic-stable-structures.workspace = true
ic-ledger-types.workspace = true
candid.workspace = true
serde.workspace = true
shared_types = { path = "../shared_types" }